Front
LatropAgency/itechart-pylab-2021 pull request #3
Opened 2021-02-09 09:08 UTC by LatropAgency

2021-02-12 10:00 UTC, alexkudelin commented on assignment2/async.py
> +    month_list = {
А ситуация, что дата не по-русски написана, исключена?

2021-02-12 10:02 UTC, alexkudelin commented on assignment2/server.py
> +        with open('index.html') as f:
Что-то пошло не так :)
Нам это не надо в сервере. Подразумевается, что я открываю index.html и там получаю все что нужно. Этот метод тут совершенно не нужен

2021-02-12 10:15 UTC, alexkudelin commented on assignment2/storage.py
>          'DELETE': 'DELETE FROM posts WHERE post_uuid = %s',
Давай всю эту коллекцию уберем отсюда, превратив это в папку с шаблонами

2021-02-12 11:08 UTC, alexkudelin commented on assignment2/storage.py
> +        'SELECT_ALL': 'SELECT DISTINCT category FROM posts',
Я бы завел таблицу для категорий и сделал из таблицы с постами ссылку на таблицу с категориями вместо конкретного столбца с конкретными названиями категорий

2021-02-12 11:09 UTC, alexkudelin commented on assignment2/index.html
> +    async function getPosts(page = 0, count = 5, date = null, category = null) {
Надо выселить в отдельный файл-модуль весь js-код и сюда просто завести энтрипоинт в этот модуль

2021-02-12 11:09 UTC, alexkudelin requested changes
Отписал в комментариях. Есть над чем поработать, но уже почти то, что нужно

2021-02-15 11:38 UTC, alexkudelin commented on assignment2/server.py
> +                r'^/$': self.get_page,
Надо убирать все то, что не решает задачу API из эндпоинтов. Этого явно тут не должно быть. Проблему с CORS нужно разруливать заголовками запросов и ответов. Вход в фронтовую часть приложения происходит из файла index.html, в которой встроен js-код, который подгружает всю инфу с бэкэнда.

2021-02-15 11:38 UTC, alexkudelin commented on assignment2/server.py
> +    def get_script(self):
Не нужно по причине выше

2021-02-15 11:44 UTC, alexkudelin commented on assignment2/db/categories.py
> +SELECT_ALL = 'SELECT * FROM categories'
Когда я говорил про разделение скриптов по файлам, я имел ввиду конкретно систему "1 скрипт - 1 файл". Причем файл не питоновский, а какой-то типа *.tmpl.
Например, будет файл get_categories.tmpl, в котором будет скрипт:
```
select category_id from categories where name = %s
```

Сверх того, я бы попробовал еще добить это дело шаблонизатором из psycopg2, чтобы сделать скрипты более гибкими -- чтобы они могли как принимать какие-то параметры, так и не принимать, например, пагинацию или фильтрацию

Дока, от которой можно попробовать оттолкнуться: https://www.psycopg.org/docs/sql.html

2021-02-15 12:02 UTC, alexkudelin commented on assignment2/storage.py
> +            cursor.execute(categories_.DELETE)
Удаление поста ведет к удалению юзера и категории? По-моему, где-то здесь закралась логическая ошибка
Тем более, если ты используешь FOREIGN KEY, то можно задать поведение зависимого объекта при удалении объекта, от которого он зависит

2021-02-15 12:03 UTC, alexkudelin commented on assignment2/storage.py
> +            cursor.execute(posts_.SELECT_USER_ID, (uuid,))
Какой-то могучий апдейт. У тебя все в кучу апдейтится?

2021-02-15 12:03 UTC, alexkudelin commented on scripts/3.create_categories.sql
> +    category_id serial PRIMARY KEY,
Может быть, просто `id`?

2021-02-15 12:04 UTC, alexkudelin requested changes
Отписал в комментариях замечания и пожелания

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +                        return (
use destructuring this.props.posts.map(({post_uuid, username, category}) =>

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +class LoadPosts extends React.Component {
prefer functional component if there are no state or lifecicle methods 
const LoadPosts = ({changePost}) => <button onClick={changePost}>Load more</button>

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +        return <button onClick={() => this.props.changePost()}>Load more</button>
in this case you create new function for every single render that decreases react performance. it is unnecessary. use like on previous example

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +        return <input type="date" onSelect={(e) => {
in this case better to create method instead lambda prop

class DateFilter extends React.Component {
        onSelect = (e) => {
                     this.props.changeDate(e.target.value)
        }

        render() {
            return <input type="date" onSelect={onSelect}/>
        }
}

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +        this.setState((state) => ({'categories': categories}))
this.setState(({categories})) 
new state not related to previous. callback not necessary. and use short property recording

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +        return (<select onChange={(e) => {
avoid lambda

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +                    return (<option key={index}>{category}</option>)
if list have ids use it instead array index

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +    render() {
use destructuring 
const {posts, isVisible} = this.state

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +        await this.changePost()
need catch errors in async componentDidMount

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +        this.state.page = 0
remove this.state.smth assignments. it is pointless

2021-02-15 19:25 UTC, gitkoshelew commented on assignment2/common.js
> +        this.setState((state) => ({posts: newPosts, page: state.page + 1}))
looks like better unite  2 setStates             
this.setState((state) => ({isVisible: true}))
        this.setState((state) => ({posts: newPosts, page: state.page + 1}))

2021-02-15 21:09 UTC, LatropAgency commented on assignment2/common.js
> +                    return (<option key={index}>{category}</option>)
backend sends only names

2021-02-16 09:26 UTC, alexkudelin commented on assignment2/categories.py
> +SELECT_ALL = 'SELECT * FROM categories'
Этот файл остается?

2021-02-16 09:27 UTC, alexkudelin commented on assignment2/db/category/delete_category.tmpl
> +DELETE FROM categories WHERE category_id NOT IN (SELECT category_id FROM posts)
А в чем сакральный смысл удаления категорий? Почему бы им не остаться, даже если постов такой категории нет?

2021-02-16 09:30 UTC, alexkudelin commented on assignment2/db/category/select_category.tmpl
> +SELECT category_id FROM categories where name = %s
В отдельных случаях имеет смысл делать поиск регистронезависимым. Зависит от конкретной ситуации. Если у тебя категории, например, `WhatCouldGoWrong` и `whatcouldgowrong` являются разными, то поиск будет регистрозависимый. Если же они одинаковые, то нужно делать регистронезависимым

2021-02-16 09:30 UTC, alexkudelin commented on assignment2/db/category/update_categoy.tmpl
> +UPDATE categories SET name=%s WHERE category_id = %s
Опечатка в названии файла

2021-02-16 09:30 UTC, alexkudelin commented on assignment2/db/post/select_category.tmpl
> +SELECT p.post_uuid, p.url, u.username, u.user_karma, u.cake_day, u.post_karma, u.comment_karma, p.post_date, p.comment_count, p.vote_count, c.name as category FROM posts AS p INNER JOIN users AS u ON
Надо отформатировать запрос. Читать сложно

2021-02-16 09:31 UTC, alexkudelin commented on assignment2/db/post/select_date.tmpl
> +SELECT p.post_uuid, p.url, u.username, u.user_karma, u.cake_day, u.post_karma, u.comment_karma, p.post_date, p.comment_count, p.vote_count, c.name as category FROM posts AS p INNER JOIN users AS u ON
Форматирование надо поправить

2021-02-16 09:31 UTC, alexkudelin commented on assignment2/db/post/select_date_category.tmpl
> +SELECT p.post_uuid, p.url, u.username, u.user_karma, u.cake_day, u.post_karma, u.comment_karma, p.post_date, p.comment_count, p.vote_count, c.name as category FROM posts AS p INNER JOIN users AS u ON
Форматирование надо поправить

2021-02-16 09:31 UTC, alexkudelin commented on assignment2/db/post/select_posts.tmpl
> +SELECT posts.post_uuid, posts.url, users.username, users.user_karma, users.cake_day, users.post_karma, users.comment_karma, posts.post_date, posts.comment_count, posts.vote_count, categories.name as
Форматирование надо поправить

2021-02-16 09:31 UTC, alexkudelin commented on assignment2/db/post/update_post.tmpl
> +UPDATE posts SET url=%s, post_date=%s, comment_count=%s, vote_count=%s WHERE post_uuid = %s
Форматирование надо поправить

2021-02-16 09:36 UTC, alexkudelin commented on assignment2/db/user/delete_user.tmpl
> +DELETE FROM users WHERE user_id NOT IN (SELECT user_id FROM posts)
Есть ли смысл удалять пользователей, если нет постов, с которыми они связаны?

2021-02-16 09:36 UTC, alexkudelin commented on assignment2/posts.py
> +INSERT = 'INSERT INTO posts(url, post_date, comment_count, vote_count, category_id, user_id) VALUES(%s, %s, %s, %s, %s, %s) RETURNING post_uuid'
Файл тоже остается?

2021-02-16 09:37 UTC, alexkudelin commented on assignment2/server.py
> +                r'^/script/$': self.get_script,
Оно нужно?

2021-02-16 09:39 UTC, alexkudelin requested changes
Есть еще что исправить

2021-02-18 08:36 UTC, alexkudelin approved these changes
LGTM

2021-02-19 18:05 UTC, merged